version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: portfolio_mysql
    environment:
      MYSQL_ROOT_PASSWORD: PaoloSid6189*
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: paolo
      MYSQL_PASSWORD: PaoloSid6189*
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: