@api = http://localhost:5000/api

GET {{api}}/users
Content-Type: application/json

###

GET {{api}}/users/1
Content-Type: application/json

###
POST {{api}}/users
Content-Type: application/json

{
    "name": "paolo",
    "last_name": "salazar",
    "second_last_name": "villarroel",
    "email": "paolo.salazar@example.com",
    "password": "salazar"
}

### 
POST {{api}}/users
Content-Type: application/json

{
    "name": "jhymy",
    "last_name": "rodriguez",
    "email": "jhimy.rodriguez@example.com",
    "password": "rodriguez"
}