"""Initial migration

Revision ID: 6068a5823fdc
Revises: aa2c67f871b2
Create Date: 2025-11-21 06:50:40.922473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6068a5823fdc'
down_revision = 'aa2c67f871b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
