"""Added contact type entity 

Revision ID: 80013ac661bc
Revises: 5ad689f9dcb4
Create Date: 2025-11-28 03:22:28.568507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80013ac661bc'
down_revision = '5ad689f9dcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_types')
    # ### end Alembic commands ###
