"""Added lastname and secondlastname fields to user

Revision ID: ce7cb47286be
Revises: 68fb6d23bdfc
Create Date: 2025-11-26 05:25:44.910016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7cb47286be'
down_revision = '68fb6d23bdfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('second_last_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('second_last_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
