"""Rename value to link_or_number in user_contacts

Revision ID: d4e5f6g7h8i9
Revises: c3d4e5f6g7h8
Create Date: 2025-12-19 10:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e5f6g7h8i9'
down_revision = 'c3d4e5f6g7h8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_contacts', schema=None) as batch_op:
        batch_op.alter_column(
            'value',
            new_column_name='link_or_number',
            existing_type=sa.String(length=255),
            existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_contacts', schema=None) as batch_op:
        batch_op.alter_column(
            'link_or_number',
            new_column_name='value',
            existing_type=sa.String(length=255),
            existing_nullable=False
        )

    # ### end Alembic commands ###